### ISSUE TITLE
acsoo pr-status: To html

### ISSUE THREAD

**Issue by rousseldenis** [acsone/acsoo#84]
A good improvement could be an argument to generate an html page (or fragment) for acsoo pr-status.

That page could be included in projects pages or ...

@sbidoul What do you think ?

**Comment by sbidoul** [comment]
Why would it be more useful than printing text with links on the terminal ?

**Comment by rousseldenis** [comment]
> Why would it be more useful than printing text with links on the terminal ?

Indeed
