### ISSUE TITLE
mrbob acsoo:templates/project fails

### ISSUE THREAD

**Issue by rousseldenis** [acsone/acsoo#86]
- acsoo installed with pipx
- mr.bob installed with pipx

![image](https://user-images.githubusercontent.com/19529533/134810495-f8b66cc6-16ba-4ba0-8e6d-472cea1c790b.png)

I think it was working on python2.7.

**Comment by sbidoul** [comment]
You need to install templates in the same environment as mrbob.

**Comment by rousseldenis** [comment]
Indeed, so, not possible to use user's one.

**Comment by sbidoul** [comment]
The project template is being removed. See https://github.com/acsone/acsone-odoo-project-template
